# Generated by Django 4.2.29 on 2026-03-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='whatsapp_keyword',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
