# Generated by Django 4.2.29 on 2026-03-07 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_businessprofile_business_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='whatsapp_keyword',
        ),
    ]
