# Generated by Django 4.2.29 on 2026-03-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_businessprofile_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='booking_policies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='services_offered',
            field=models.TextField(blank=True),
        ),
    ]
