# Generated by Django 4.2.29 on 2026-03-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_notification_is_read_notification_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
