# Generated by Django 4.2.30 on 2026-04-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_businessprofile_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='vapi_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='vapi_assistant_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
