# Generated by Django 4.2.29 on 2026-03-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.BigIntegerField()),
                ('received_message', models.TextField(blank=True, null=True)),
                ('sent_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('contact_number', 'timestamp', 'received_message', 'sent_message')},
            },
        ),
    ]
