# Generated by Django 4.2.29 on 2026-03-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversationlog',
            unique_together={('contact_number', 'timestamp')},
        ),
    ]
