# Generated by Django 4.2.29 on 2026-03-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_conversationlog_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('tool_call_id', models.CharField(max_length=200, unique=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_id', models.CharField(blank=True, max_length=100, null=True)),
                ('business_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('services_offered', models.CharField(blank=True, max_length=500, null=True)),
                ('booking_policies', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('appointment_datetime', models.DateTimeField(blank=True, null=True)),
                ('service', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['appointment_datetime'],
            },
        ),
    ]
