# Generated by Django 4.2.29 on 2026-03-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_datetime']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='action',
            field=models.CharField(blank=True, default='To Sync', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=50, null=True),
        ),
    ]
