# Generated by Django 4.2.29 on 2026-03-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_appointment_options_appointment_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='action',
            field=models.CharField(blank=True, default='No', max_length=50, null=True),
        ),
    ]
