# Generated by Django 4.2.29 on 2026-03-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_appointment_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_synced_to_sheets',
            field=models.BooleanField(default=False),
        ),
    ]
