# Generated by Django 4.2.29 on 2026-03-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_appointment_is_synced_to_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='overdue_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
