# Generated by Django 4.2.29 on 2026-03-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_appointment_overdue_sent_appointment_reminder_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_synced_to_sheets',
        ),
    ]
